baseURL = "https://codechauffeur.com"
languageCode = "en-uk"
title = "Code Chauffeur"
email = "emmanuel@codechauffeur.com"
linkedin = "https://www.linkedin.com/in/emmanuel-awotunde"
github = "https://github.com/olaoluwa-98"
theme = "beyondnothing"
copyright = "© Emmanuel Awotunde"
home = "https://codechauffeur.com"

googleAnalytics = "UA-92329943-4"

[author]
  name = "Emmanuel Awotunde"
  homepage = "https://codechauffeur.com"

[params]
    title = "Code Chauffeur"
    images = ["/images/logo.png"]
    description = "Software engineering should be as fun as a ride, let's take the ride together🚗"
    hidefromhome = "true"

# Pagination
paginate = 25
paginatePath = "page"


# Taxonomies
[taxonomies]
    tag = "tags"

# Menu
[menu]
    # Header
    [[menu.main]]
        url = "/"
        name = "Home"
        weight = 1
    [[menu.main]]
        url = "/articles/"
        name = "Articles"
        weight = 2
    [[menu.main]]
        url = "/contact/"
        name = "Contact"
        weight = 3
    [[menu.main]]
        url = "/portfolio/"
        name = "Portfolio"
        weight = 4
    [[menu.main]]
        url = "/podcast/"
        name = "Podcast"
        weight = 5

    # Footer
    [[menu.footer]]
      [[menu.footer]]
        url = "https://www.linkedin.com/in/emmanuel-awotunde"
        name = "Linkedin"
        weight = 1
    [[menu.footer]]
        url = "https://github.com/olaoluwa-98"
        name = "GitHub"
        weight = 2
    [[menu.footer]]
        url = "mailto:emmanuel@codechauffeur.com"
        name = "Email"
        weight = 3
    [[menu.footer]]
        url = "/articles/index.xml"
        name = "RSS"
        weight = 4

enableRobotsTXT = true
canonifyURLs = true

# Links format
[permalinks]
    articles = "/:slug/"
    tags = "/tags/:slug/"
